# SITE CONFIGURATION
title: Zonggen's Nomadic Life # your site title
author: zonggen # You :P
description: > # Meta description of Homepage
  Zonggen's personal blogging website and lifestyle at U of T.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zonggen.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Zonggen Bai
  links:
    - https://www.linkedin.com/in/zonggen-bai-4131ba151/
    - https://github.com/zonggen

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Hi there! I'm a current CS student and former Biomedical Science student. Let's talk!

hero_img: posts/homepage_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: carpe.diem.allen@gmail.com # email for form submission

github_username:  zonggen # replace with your_github_username or comment to remove link from footer

disqus:
  shortname: zonggen # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
